name: nph8
favicon: null
layout_spectrum: 0.39825
typography_spectrum: 0.16849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1282d'
    - '#13161d'
    - '#e7aa8e'
    - '#393e42'
    - '#5f6973'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
