name: nph8
favicon: null
layout_spectrum: 0.10426579089835286
typography_spectrum: 0.9439452770166099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0a0b'
    - '#999187'
    - '#574e49'
    - '#eceade'
    - '#c5bdb1'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
